[package]
name = "uniplate"
version = "0.1.0-beta.1"
authors = ["Niklas Dewally <niklas@dewally.com>","Ozgur Akgun"]
edition = "2021"
description = "Boilerplate-free, generic tree traversals"
readme = "README.md"
repository = "https://github.com/conjure-cp/uniplate"
license = "MPL-2.0"
keywords = ["macro"]
categories = ["rust-patterns","data-structures","algorithms","parsing"]

[lib]

[dependencies]
im = {version = "15.1.0", features = ["proptest"]}
proptest = "1.5.0"
proptest-derive = "0.5.0"
thiserror = "1.0.61"
uniplate-derive = {path="../uniplate-derive"}

[dev-dependencies]
trybuild = "1.0.91"

#[lints]
#workspace = true

[features]
unstable = []


