[package]
name = "uniplate"
version = "0.1.0-beta.1"
edition = "2021"
description="Boilerplate-free generic operations on data, Haskell style."
license = "MPL-2.0"

[lib]

[dependencies]
im = {version = "15.1.0", features = ["proptest"]}
proptest = "1.5.0"
proptest-derive = "0.5.0"
thiserror = "1.0.61"
uniplate-derive = {path="../uniplate-derive"}

[dev-dependencies]
trybuild = "1.0.91"

#[lints]
#workspace = true

[features]
unstable = []


