# see: https://github.com/marketplace/actions/rust-rustfmt-check

name: "rustfmt check"

on:
  push:
    branches:
      - main # run for pushes to the main branch
    paths:
      - uniplate/**
      - uniplate-derive/**
      - .github/actions/format.yml
  pull_request:
    paths:
      - uniplate/**
      - uniplate-derive/**
      - .github/actions/format.yml
  workflow_dispatch:

jobs:
  rust:
    name: "Check Rust Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check
