name: "build and test"

on:
  push:
    branches:
      - main # run for pushes to the main branch. other branches need to create a PR if they want testing.
    paths: 
      - uniplate/**
      - uniplate-derive/**
      - .github/actions/test.yml
  pull_request:
    paths: 
      - uniplate/**
      - uniplate-derive/**
      - .github/actions/test.yml
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build and Test"
    strategy:
      # run all combinations of the matrix even if one combination fails.
      fail-fast: false
      matrix:
        rust_release:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.rust_release }} && rustup default ${{ matrix.rust_release }}
      - run: cargo build -vv --workspace
      - run: cargo test --workspace

  audit:
    name: "Dependency Audit"
    runs-on: ubuntu-latest
    strategy:
      # run all combinations of the matrix even if one combination fails.
      fail-fast: false
      matrix:
        rust_release:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.rust_release }} && rustup default ${{ matrix.rust_release }}
      - run: cargo audit
